services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: smart_exam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d smart_exam']
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgres://postgres:postgres@db:5432/smart_exam
      JWT_SECRET: change_me_to_a_long_random_secret
      CLIENT_ORIGIN: http://localhost:8080
      ADMIN_EMAIL: admin@exam.local
      ADMIN_PASSWORD: Admin12345!
      ADMIN_NAME: Sistem Admini
      MAX_UPLOAD_MB: 10
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '4000:4000'

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '8080:80'

volumes:
  pgdata:
